# Generated by Django 2.2.2 on 2019-06-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curriculum',
            new_name='Technology',
        ),
    ]
