# Generated by Django 2.2.2 on 2019-06-13 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sb_app', '0002_auto_20190613_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo_url',
            new_name='age',
        ),
    ]
